### PR TITLE
admin can take a business online/offline

### PR DESCRIPTION
**Pull request by twhitinger**

### CODE REVIEW

**Comment by MsJennyGiraffe** [comment]
One failing test, I think Matt fixed it with his PR, I assume it'll be okay?

**Comment by matthewecampbell** [comment]
Yeah, I fixed that test.  We are good to go!

**Comment by MsJennyGiraffe** [comment]
Cool! Merge it in?

**Comment by matthewecampbell** [comment]
You know it.

**Comment by twhitinger** [comment]
thanks guys i was super confused now I'm super happy

**Comment by MsJennyGiraffe** [comment]
Everything passes on dev now, good job guys!

**Pull request merged**
